### ISSUE TITLE
No effects on Win 8.1 Italian x64

### ISSUE THREAD

**Issue by gianluigiloffreda** [broken-e/DragDropConfirm#1]
Hi, 

this tool was exactly what I was looking for but I just installed it on my PC and it seems not to do anything at all.
After a reboot I can move files and folders as before without any popup message.
Is there anything to make it works?
Thanks

**Comment by broken-e** [comment]
Hi, thanks for the report. I'm not currently able to test on your particular platform, Windows 8.1 Italian x64. Have you by chance tried it on another PC with the same OS version or similar? It could be due to the language support if the issue has that as a common factor, since I have had reports of it working on Windows 8.1 English x64.

**Comment by gianluigiloffreda** [comment]
Hi. I just tried on a Windows 7 x64 Pro SP1 (Italian) and also there it doesn't seem to have any effect.
Below the steps I followed:
1. Insalled Visual C++ Redistributable Package from this link
http://www.microsoft.com/it-it/download/details.aspx?id=30679

2. Installed the dragdropinterceptor EXE
3. Reboot
4. Open a Windows Explorer
5. Created a new folder with a new txt file inside
6. Tried to move the folder in another position.
7. It just moved without any popup message

Thanks for your support.
If you have any tip or something I can test I'll be happy to help.

Gianluigi

**Comment by gianluigiloffreda** [comment]
Hi. I read a comment on your website (broken-e.com) by another user and it seems he have a similar problem.

It seems that your software doesn't work on non-English systems. Is there any way to fix it?

Thank you

**Comment by broken-e** [comment]
@gianluigiloffreda I have released a new version which should provide an effective workaround for you. Please check the [Advanced Instructions](http://broken-e.com/dragdropconfirm-instructions) on a way to customize the underlying menu item value to be appropriate for other languages. It currently checks for the string `&Move here` but can be customized by adding a registry value as described in the instructions. Please let me know if this works for you.

**Comment by gianluigiloffreda** [comment]
Thanks. 
Now it works perfectly. 

Great job. 

Gianluigi


Inviato da iPhone
